#ifndef LAYER_TABLE_H
#define LAYER_TABLE_H

/* AUTO-GENERATED by training/train.py — DO NOT EDIT.
 * Re-generate after every re-train. */

#include "layer_desc.h"

/* NUM_LAYERS is compile-time (loop bound). LAYERS data lives in D-BRAM at
 * 0xB0040800 — ARM loads layer_table.bin there before kicking RISC-V. */
#define NUM_LAYERS  7u
#define LAYERS      ((const layer_desc_t*)0xB0040800u)

#endif /* LAYER_TABLE_H */
