#ifndef LAYER_TABLE_H
#define LAYER_TABLE_H

/* AUTO-GENERATED bởi training/train.py — DO NOT EDIT.
 * Re-generate sau mỗi lần re-train. */

#include "layer_desc.h"

const uint32_t NUM_LAYERS = 5;

const layer_desc_t LAYERS[5] = {
    [0] = {
        .weight_offset = 0u,
        .weight_bytes  = 216u,
        .bias_offset   = 0xd8u,
        .bias_bytes    = 32u,
        .ifm_width     = 128,
        .ifm_height    = 128,
        .cin           = 3,
        .cout          = 8,
        .kernel        = 3,
        .stride        = 1,
        .padding       = 0,
        .pool_en       = 0,
        .activation    = 1,
        ._reserved     = {0, 0, 0},
        .output_M      = 1410779779,
        .output_shift  = 9,
        .input_zp      = -128,
        .output_zp     = -128,
        .weight_zp     = 0,
    },
    [1] = {
        .weight_offset = 248u,
        .weight_bytes  = 1152u,
        .bias_offset   = 0x578u,
        .bias_bytes    = 64u,
        .ifm_width     = 126,
        .ifm_height    = 126,
        .cin           = 8,
        .cout          = 16,
        .kernel        = 3,
        .stride        = 1,
        .padding       = 0,
        .pool_en       = 0,
        .activation    = 1,
        ._reserved     = {0, 0, 0},
        .output_M      = 1130672946,
        .output_shift  = 8,
        .input_zp      = -128,
        .output_zp     = -128,
        .weight_zp     = 0,
    },
    [2] = {
        .weight_offset = 1464u,
        .weight_bytes  = 4608u,
        .bias_offset   = 0x17b8u,
        .bias_bytes    = 128u,
        .ifm_width     = 124,
        .ifm_height    = 124,
        .cin           = 16,
        .cout          = 32,
        .kernel        = 3,
        .stride        = 1,
        .padding       = 0,
        .pool_en       = 0,
        .activation    = 1,
        ._reserved     = {0, 0, 0},
        .output_M      = 1522697144,
        .output_shift  = 9,
        .input_zp      = -128,
        .output_zp     = -128,
        .weight_zp     = 0,
    },
    [3] = {
        .weight_offset = 6200u,
        .weight_bytes  = 18432u,
        .bias_offset   = 0x6038u,
        .bias_bytes    = 256u,
        .ifm_width     = 122,
        .ifm_height    = 122,
        .cin           = 32,
        .cout          = 64,
        .kernel        = 3,
        .stride        = 1,
        .padding       = 0,
        .pool_en       = 0,
        .activation    = 1,
        ._reserved     = {0, 0, 0},
        .output_M      = 1805295645,
        .output_shift  = 9,
        .input_zp      = -128,
        .output_zp     = -128,
        .weight_zp     = 0,
    },
    [4] = {
        .weight_offset = 24888u,
        .weight_bytes  = 1152u,
        .bias_offset   = 0x65b8u,
        .bias_bytes    = 8u,
        .ifm_width     = 120,
        .ifm_height    = 120,
        .cin           = 64,
        .cout          = 2,
        .kernel        = 3,
        .stride        = 1,
        .padding       = 0,
        .pool_en       = 0,
        .activation    = 0,
        ._reserved     = {0, 0, 0},
        .output_M      = 1498358286,
        .output_shift  = 10,
        .input_zp      = -128,
        .output_zp     = -68,
        .weight_zp     = 0,
    },
};

#endif /* LAYER_TABLE_H */
